name: Terraform Plan

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Init & Plan (S3)
        working-directory: terraform/01-s3-bucket
        run: |
          terraform init -input=false
          terraform fmt -check -recursive
          terraform validate
          terraform plan -input=false -out=tfplan
